/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Institute;

import static java.lang.String.valueOf;
import java.sql.Connection;
import java.sql.Date;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.Statement;
import java.sql.Time;
import java.util.ArrayList;
import java.util.Arrays;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import static javax.swing.text.html.HTML.Attribute.ID;

/**
 *
 * @author johnh
 */
public class Add_Working_Days_and_Hours extends javax.swing.JFrame {
    Add_working_Days_And_Hours_Model add_working_days_and_hours_model = new Add_working_Days_And_Hours_Model();
    public Add_Working_Days_and_Hours() {
        initComponents();
    }
   
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();
        jButton10 = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jCheckBox2Monday = new javax.swing.JCheckBox();
        jCheckBox3Wednesday = new javax.swing.JCheckBox();
        jCheckBox4Tuesday = new javax.swing.JCheckBox();
        jCheckBox5Thursday = new javax.swing.JCheckBox();
        jCheckBox6Friday = new javax.swing.JCheckBox();
        jCheckBox7Sunday = new javax.swing.JCheckBox();
        jCheckBox8Saturday = new javax.swing.JCheckBox();
        jLabel5 = new javax.swing.JLabel();
        jSpinner2Hours = new javax.swing.JSpinner();
        jLabel6 = new javax.swing.JLabel();
        jSpinner3Minutes = new javax.swing.JSpinner();
        jLabel7 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton11 = new javax.swing.JButton();
        jComboBox1NoOfWorkingDays = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTblAddWork = new javax.swing.JTable();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setForeground(new java.awt.Color(204, 102, 255));

        jPanel1.setBackground(new java.awt.Color(48, 143, 153));

        jLabel2.setFont(new java.awt.Font("ROG Fonts", 0, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Higher National Information Technology Institute");
        jLabel2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(350, 350, 350)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 895, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(16, Short.MAX_VALUE)
                .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(69, 69, 69))
        );

        jPanel2.setBackground(new java.awt.Color(0, 204, 204));

        jButton3.setBackground(new java.awt.Color(102, 204, 255));
        jButton3.setText("Lecturers");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setBackground(new java.awt.Color(153, 255, 153));
        jButton4.setText("Students");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jButton5.setBackground(new java.awt.Color(255, 153, 51));
        jButton5.setText("Subjects");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jButton6.setBackground(new java.awt.Color(255, 255, 102));
        jButton6.setText("Tags");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        jButton7.setBackground(new java.awt.Color(255, 153, 153));
        jButton7.setText("Sessions");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });

        jButton8.setBackground(new java.awt.Color(255, 153, 255));
        jButton8.setText("Add Working\nDays & Hours");
        jButton8.setToolTipText("");
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });

        jButton9.setBackground(new java.awt.Color(153, 153, 153));
        jButton9.setText("Generate Time Table");
        jButton9.setToolTipText("");
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });

        jButton10.setBackground(new java.awt.Color(0, 255, 255));
        jButton10.setText("Location");
        jButton10.setToolTipText("");
        jButton10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton10ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButton3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton8, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton3, javax.swing.GroupLayout.DEFAULT_SIZE, 48, Short.MAX_VALUE)
                    .addComponent(jButton7, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        jPanel3.setBackground(new java.awt.Color(153, 153, 153));

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 153, 255));
        jLabel1.setText("Add Working Days & Hours ");

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel3.setText("Number of Working Days");

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel4.setText("Working Days");

        jCheckBox2Monday.setText("Monday");
        jCheckBox2Monday.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox2MondayActionPerformed(evt);
            }
        });

        jCheckBox3Wednesday.setText("Wednesday");
        jCheckBox3Wednesday.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox3WednesdayActionPerformed(evt);
            }
        });

        jCheckBox4Tuesday.setText("Tuesday");
        jCheckBox4Tuesday.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox4TuesdayActionPerformed(evt);
            }
        });

        jCheckBox5Thursday.setText("Thursday");

        jCheckBox6Friday.setText("Friday");

        jCheckBox7Sunday.setText("Sunday");

        jCheckBox8Saturday.setText("Saturday");

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel5.setText("Working Time Per Day");

        jSpinner2Hours.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        jLabel6.setText("Hours");

        jSpinner3Minutes.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                jSpinner3MinutesPropertyChange(evt);
            }
        });

        jLabel7.setText("Minutes");

        jButton1.setBackground(new java.awt.Color(102, 204, 255));
        jButton1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton1.setText("SAVE");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton11.setBackground(new java.awt.Color(255, 102, 102));
        jButton11.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton11.setText("DELETE");
        jButton11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton11ActionPerformed(evt);
            }
        });

        jComboBox1NoOfWorkingDays.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select", "1", "2", "3", "4", "5", "6", "7" }));
        jComboBox1NoOfWorkingDays.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1NoOfWorkingDaysActionPerformed(evt);
            }
        });

        jTblAddWork.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.gray, java.awt.Color.lightGray, java.awt.Color.black, java.awt.Color.darkGray));
        jTblAddWork.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jTblAddWork.setForeground(new java.awt.Color(0, 153, 153));
        jTblAddWork.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "                  ID", " Number of Working Days", "       Working Days", "   Working Time Per Day"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.Integer.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTblAddWork.getTableHeader().setReorderingAllowed(false);
        jTblAddWork.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTblAddWorkMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTblAddWork);

        jButton2.setBackground(new java.awt.Color(255, 204, 51));
        jButton2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton2.setText("UPDATE");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(250, 250, 250)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 904, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(235, 235, 235)
                                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(234, 234, 234)
                                .addComponent(jButton11, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(38, 38, 38)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addComponent(jSpinner2Hours, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(0, 0, 0)
                                        .addComponent(jSpinner3Minutes, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(0, 0, 0)
                                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addComponent(jCheckBox2Monday, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jCheckBox4Tuesday, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jCheckBox3Wednesday, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jCheckBox5Thursday, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jCheckBox6Friday, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(jComboBox1NoOfWorkingDays, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jCheckBox8Saturday, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jCheckBox7Sunday, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(600, 600, 600)
                        .addComponent(jLabel1)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(90, 90, 90)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jComboBox1NoOfWorkingDays, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jCheckBox2Monday, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jCheckBox4Tuesday, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jCheckBox3Wednesday, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jCheckBox5Thursday, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jCheckBox6Friday, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jCheckBox8Saturday, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jCheckBox7Sunday, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jSpinner3Minutes, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jSpinner2Hours, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(37, 37, 37)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(53, 53, 53)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton11, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(182, 182, 182))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        Lecturers lec = new   Lecturers();
        lec.setVisible(true);
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        Tags tag = new   Tags();
        tag.setVisible(true);
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        Sessions sub = new   Sessions();
        sub.setVisible(true);
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        Add_Working_Days_and_Hours Awd = new   Add_Working_Days_and_Hours();
        Awd.setVisible(true);
    }//GEN-LAST:event_jButton8ActionPerformed

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton9ActionPerformed

    private void jButton10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton10ActionPerformed
       Locations loca = new   Locations();
        loca.setVisible(true);
    }//GEN-LAST:event_jButton10ActionPerformed

    private void jButton11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton11ActionPerformed
      
       
       
        if(jTblAddWork.getSelectedRowCount()==1){
             DefaultTableModel tblModel = (DefaultTableModel)jTblAddWork.getModel();
        Integer NumberOfWorkingDays =  jComboBox1NoOfWorkingDays.getSelectedIndex();
        String WorkingDays = "";
        if(jCheckBox2Monday.isSelected() ){
         WorkingDays += jCheckBox2Monday.getText() ;
        }
            if (jCheckBox4Tuesday.isSelected()){
               WorkingDays +=  "," +  jCheckBox4Tuesday.getText();
            }
                if (jCheckBox3Wednesday.isSelected()){
                    WorkingDays += "," +  jCheckBox3Wednesday.getText();
                }
                    if (jCheckBox5Thursday.isSelected()){
                        WorkingDays += "," +  jCheckBox5Thursday.getText();    
                    }
                        if(jCheckBox6Friday.isSelected()){
                            WorkingDays += "," +  jCheckBox6Friday.getText();    
                        }
                            if(jCheckBox8Saturday.isSelected()){
                                WorkingDays += "," +  jCheckBox8Saturday.getText();    
                            }
                                if(jCheckBox7Sunday.isSelected()){
                                        WorkingDays += "," +  jCheckBox7Sunday.getText();    
                                    }
                
        String WorkingTimePerDay = (String) jSpinner2Hours.getValue().toString() + " hrs " +(String) jSpinner3Minutes.getValue().toString() + " mins";
        
        int row = jTblAddWork.getSelectedRow();
             
        Integer ID = (Integer) jTblAddWork.getModel().getValueAt(row, 0);
        
        
        add_working_days_and_hours_model.insertUpdateDeleteAdd_working_Days_And_Hours_Model('d',ID, NumberOfWorkingDays, WorkingDays , WorkingTimePerDay);
         
        }
        
        jTblAddWork.setModel(new DefaultTableModel(null,new Object[]{ID,"Number_of_Working_Days","Working_Days","Working_Time_Per_Day"}));  

       
        
        try{
           
               Class.forName("com.mysql.jdbc.Driver");
               Connection con = DbConnection.dbconnect();
                 DefaultTableModel tblModel = (DefaultTableModel)jTblAddWork.getModel();
               Statement st=con.createStatement();
               ResultSet rs = st.executeQuery("SELECT * FROM hniti.add_working_days_and_hours");
               while(rs.next()){
                   
                    
       
                   Integer ID = rs.getInt("ID");
                    Integer NumberOfWorkingDays = rs.getInt("Number_of_Working_Days");
                    String WorkingDays = rs.getString("Working_Days");
                   String WorkingTimePerDay= rs.getString("Working_Time_Per_Day");
               
                  tblModel.addRow(new Object[]{ID, NumberOfWorkingDays, WorkingDays, WorkingTimePerDay});
               }
                 
                    
               
               jTblAddWork.setModel(tblModel);
               
            }
               

        catch(Exception e){
            
        }
        
    }//GEN-LAST:event_jButton11ActionPerformed

    private void jCheckBox4TuesdayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox4TuesdayActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCheckBox4TuesdayActionPerformed

    private void jCheckBox3WednesdayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox3WednesdayActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCheckBox3WednesdayActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        Integer NumberOfWorkingDays = jComboBox1NoOfWorkingDays.getSelectedIndex();
        String WorkingDays="";
        
        if(jCheckBox2Monday.isSelected() ){
         WorkingDays += jCheckBox2Monday.getText() ;
        }
            if (jCheckBox4Tuesday.isSelected()){
               WorkingDays +=  "," +  jCheckBox4Tuesday.getText();
            }
                if (jCheckBox3Wednesday.isSelected()){
                    WorkingDays += "," +  jCheckBox3Wednesday.getText();
                }
                    if (jCheckBox5Thursday.isSelected()){
                        WorkingDays += "," +  jCheckBox5Thursday.getText();    
                    }
                        if(jCheckBox6Friday.isSelected()){
                            WorkingDays += "," +  jCheckBox6Friday.getText();    
                        }
                            if(jCheckBox8Saturday.isSelected()){
                                WorkingDays += "," +  jCheckBox8Saturday.getText();    
                            }
                                if(jCheckBox7Sunday.isSelected()){
                                        WorkingDays += "," +  jCheckBox7Sunday.getText();    
                                    }
                      
         String WorkingTimePerDay =(String) jSpinner2Hours.getValue().toString() + " hrs " +(String) jSpinner3Minutes.getValue().toString() + " mins";
         
        if( jComboBox1NoOfWorkingDays.getSelectedIndex()==0 || jCheckBox2Monday.isSelected()==false && jCheckBox4Tuesday.isSelected()==false && jCheckBox3Wednesday.isSelected()==false && jCheckBox5Thursday.isSelected()==false && jCheckBox6Friday.isSelected()==false && jCheckBox8Saturday.isSelected()==false && jCheckBox7Sunday.isSelected()==false || jSpinner2Hours.getValue().toString().equals(" ") || jSpinner3Minutes.getValue().toString().equals(" ")){
            JOptionPane.showMessageDialog(this, "Please Enter All Fields !!!");
        }
        else{
        add_working_days_and_hours_model.insertUpdateDeleteAdd_working_Days_And_Hours_Model('i',null, NumberOfWorkingDays, WorkingDays , WorkingTimePerDay);
        }
        jTblAddWork.setModel(new DefaultTableModel(null,new Object[]{ID,"Number_of_Working_Days","Working_Days","Working_Time_Per_Day"}));  
        try{
               Class.forName("com.mysql.jdbc.Driver");
               Connection con = DbConnection.dbconnect();
               DefaultTableModel tblModel = (DefaultTableModel)jTblAddWork.getModel();
               Statement st=con.createStatement();
               ResultSet rs = st.executeQuery("SELECT * FROM hniti.add_working_days_and_hours");
               while(rs.next()){
                   
                    
       
                   Integer ID = rs.getInt("ID");
                    NumberOfWorkingDays = rs.getInt("Number_of_Working_Days");
                    WorkingDays = rs.getString("Working_Days");
                    WorkingTimePerDay= rs.getString("Working_Time_Per_Day");
               
                  tblModel.addRow(new Object[]{ID, NumberOfWorkingDays, WorkingDays, WorkingTimePerDay});
               }
                 
                    
            
               jTblAddWork.setModel(tblModel);
            }
               

        catch(Exception e){
            
        }
        
            
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
       Students st = new   Students();
    st.setVisible(true);
    
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        
 Subjects sub = new   Subjects();
        sub.setVisible(true);
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jComboBox1NoOfWorkingDaysActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1NoOfWorkingDaysActionPerformed
       
        
    }//GEN-LAST:event_jComboBox1NoOfWorkingDaysActionPerformed

    private void jCheckBox2MondayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox2MondayActionPerformed
       
    }//GEN-LAST:event_jCheckBox2MondayActionPerformed

    private void jSpinner3MinutesPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_jSpinner3MinutesPropertyChange
        // TODO add your handling code here:
    }//GEN-LAST:event_jSpinner3MinutesPropertyChange

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        DefaultTableModel tblModel = (DefaultTableModel)jTblAddWork.getModel();
       
      
        
        if(jTblAddWork.getSelectedRowCount()==1){
        Integer NumberOfWorkingDays =  jComboBox1NoOfWorkingDays.getSelectedIndex();
        String WorkingDays = "";
        if(jCheckBox2Monday.isSelected() ){
         WorkingDays += jCheckBox2Monday.getText() ;
        }
            if (jCheckBox4Tuesday.isSelected()){
               WorkingDays +=  "," +  jCheckBox4Tuesday.getText();
            }
                if (jCheckBox3Wednesday.isSelected()){
                    WorkingDays += "," +  jCheckBox3Wednesday.getText();
                }
                    if (jCheckBox5Thursday.isSelected()){
                        WorkingDays += "," +  jCheckBox5Thursday.getText();    
                    }
                        if(jCheckBox6Friday.isSelected()){
                            WorkingDays += "," +  jCheckBox6Friday.getText();    
                        }
                            if(jCheckBox8Saturday.isSelected()){
                                WorkingDays += "," +  jCheckBox8Saturday.getText();    
                            }
                                if(jCheckBox7Sunday.isSelected()){
                                        WorkingDays += "," +  jCheckBox7Sunday.getText();    
                                    }
                
        String WorkingTimePerDay = (String) jSpinner2Hours.getValue().toString() + " hrs " +(String) jSpinner3Minutes.getValue().toString() + " mins";
        
        
       
        int row = jTblAddWork.getSelectedRow();
              Integer ID = (Integer) jTblAddWork.getModel().getValueAt(row, 0);
              if(jComboBox1NoOfWorkingDays.getSelectedIndex()==0 || jCheckBox2Monday.isSelected()==false && jCheckBox4Tuesday.isSelected()==false && jCheckBox3Wednesday.isSelected()==false && jCheckBox5Thursday.isSelected()==false && jCheckBox6Friday.isSelected()==false && jCheckBox8Saturday.isSelected()==false && jCheckBox7Sunday.isSelected()==false || jSpinner2Hours.getValue().toString().equals(" ") || jSpinner3Minutes.getValue().toString().equals(" ")){
         
            JOptionPane.showMessageDialog(this, "Please check  All The Fields !!!");
                }   
            else{
                    tblModel.setValueAt(NumberOfWorkingDays, jTblAddWork.getSelectedRow(), 1);
                    tblModel.setValueAt(WorkingDays, jTblAddWork.getSelectedRow(), 2);
                    tblModel.setValueAt(WorkingTimePerDay, jTblAddWork.getSelectedRow(), 3);
              add_working_days_and_hours_model.insertUpdateDeleteAdd_working_Days_And_Hours_Model('u',ID, NumberOfWorkingDays, WorkingDays, WorkingTimePerDay);
              }
//        JOptionPane.showMessageDialog(this, "Update Table Data Successfully !!!");
        }
        
         
      
        else
        {
            if(jTblAddWork.getRowCount()==0){
                JOptionPane.showMessageDialog(this, "Table is empty !!!");
            }else{
                JOptionPane.showMessageDialog(this, "Please Select a Single Row for Update  !!!");
            }
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jTblAddWorkMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTblAddWorkMouseClicked
        DefaultTableModel tblModel=(DefaultTableModel)jTblAddWork.getModel();
        int rowIndex = jTblAddWork.getSelectedRow();
        jComboBox1NoOfWorkingDays.setSelectedIndex((int) tblModel.getValueAt(rowIndex,1));
      
        
   
                jCheckBox2Monday.setSelected(false);   
                jCheckBox4Tuesday.setSelected(false);
                jCheckBox3Wednesday.setSelected(false);
                jCheckBox5Thursday.setSelected(false);
                jCheckBox6Friday.setSelected(false);
                jCheckBox8Saturday.setSelected(false);
                jCheckBox7Sunday.setSelected(false);
        
        String WorkingDays=(String) tblModel.getValueAt(rowIndex,2);
               
        
        String[] arrOfStr = WorkingDays.split(",");
        for (String a: arrOfStr){
              
         if("Monday".equals(a)){
                jCheckBox2Monday.setSelected(true);   
               
                
                  
        }else if("Tuesday".equals(a)){
            
                jCheckBox4Tuesday.setSelected(true);
               
              
              
        }else if("Wednesday".equals(a)){
           
                jCheckBox3Wednesday.setSelected(true);
              
              
               
        }else if("Thursday".equals(a)){
            
                jCheckBox5Thursday.setSelected(true);
             
                
               
                
                
        }else if("Friday".equals(a)){
           
               
                jCheckBox6Friday.setSelected(true);
                
                
                
        }else if("Saturday".equals(a)){
                jCheckBox8Saturday.setSelected(true);
             
                
               
        }else if("Sunday".equals(a)){
            
                jCheckBox7Sunday.setSelected(true);
              
        }
        }
        
         
        
      

            String sp=(String) tblModel.getValueAt(rowIndex,3);
        
            String[] arrOfWorkHours= sp.split(" ");
        
            String Str=    Arrays.toString(arrOfWorkHours);
            String hour="";
            String min="";
    
       
        
        for(int i=0;i<=Str.length();i++){
          
            if(i==0){
                hour=arrOfWorkHours[i];

                   jSpinner2Hours.setValue(Integer.valueOf(hour));
            }
            if(i==2){
                min=arrOfWorkHours[i];

                  jSpinner3Minutes.setValue(Integer.valueOf(min));
            }
        }
        
      
      
       
    }//GEN-LAST:event_jTblAddWorkMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Add_Working_Days_and_Hours.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Add_Working_Days_and_Hours.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Add_Working_Days_and_Hours.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Add_Working_Days_and_Hours.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Add_Working_Days_and_Hours().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton11;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JCheckBox jCheckBox2Monday;
    private javax.swing.JCheckBox jCheckBox3Wednesday;
    private javax.swing.JCheckBox jCheckBox4Tuesday;
    private javax.swing.JCheckBox jCheckBox5Thursday;
    private javax.swing.JCheckBox jCheckBox6Friday;
    private javax.swing.JCheckBox jCheckBox7Sunday;
    private javax.swing.JCheckBox jCheckBox8Saturday;
    private javax.swing.JComboBox<String> jComboBox1NoOfWorkingDays;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSpinner jSpinner2Hours;
    private javax.swing.JSpinner jSpinner3Minutes;
    private javax.swing.JTable jTblAddWork;
    // End of variables declaration//GEN-END:variables

} 

