/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Institute;

import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import static javax.swing.text.html.HTML.Attribute.ID;

/**
 *
 * @author johnh
 */
public class Lecturers extends javax.swing.JFrame {
    Lecturers_Model Lecturers = new Lecturers_Model();
    /**
     * Creates new form Lecturers
     */
    
    public Lecturers() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();
        jButton10 = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jTabbedPane2 = new javax.swing.JTabbedPane();
        jPanel4 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        LectureNameTF = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        EmployeeIDTF = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        FacultyCB = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        DepartmentCB = new javax.swing.JComboBox<>();
        jLabel7 = new javax.swing.JLabel();
        CenterCB = new javax.swing.JComboBox<>();
        jLabel8 = new javax.swing.JLabel();
        BuildingCB = new javax.swing.JComboBox<>();
        jLabel9 = new javax.swing.JLabel();
        LevelCB = new javax.swing.JComboBox<>();
        jLabel10 = new javax.swing.JLabel();
        RankTF = new javax.swing.JTextField();
        jButton12 = new javax.swing.JButton();
        jButton13 = new javax.swing.JButton();
        jButton14 = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTblManageLecturers = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton11 = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();
        jTF4EmployeeID = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jCB6Faculty = new javax.swing.JComboBox<>();
        jLabel14 = new javax.swing.JLabel();
        jCB7Department = new javax.swing.JComboBox<>();
        jLabel15 = new javax.swing.JLabel();
        jCB8Center = new javax.swing.JComboBox<>();
        jLabel16 = new javax.swing.JLabel();
        jCB9Building = new javax.swing.JComboBox<>();
        jLabel17 = new javax.swing.JLabel();
        jCB10Level = new javax.swing.JComboBox<>();
        jLabel18 = new javax.swing.JLabel();
        jTF5Rank = new javax.swing.JTextField();
        jTF6LectureName = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setSize(new java.awt.Dimension(0, 0));

        jPanel1.setBackground(new java.awt.Color(48, 143, 153));

        jLabel2.setFont(new java.awt.Font("ROG Fonts", 0, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Higher National Information Technology Institute");
        jLabel2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(350, 350, 350)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 895, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(16, Short.MAX_VALUE)
                .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap(69, Short.MAX_VALUE))
        );

        jPanel2.setBackground(new java.awt.Color(0, 204, 204));

        jButton3.setBackground(new java.awt.Color(102, 204, 255));
        jButton3.setText("Lecturers");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setBackground(new java.awt.Color(153, 255, 153));
        jButton4.setText("Students");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jButton5.setBackground(new java.awt.Color(255, 153, 51));
        jButton5.setText("Subjects");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jButton6.setBackground(new java.awt.Color(255, 255, 102));
        jButton6.setText("Tags");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        jButton7.setBackground(new java.awt.Color(255, 153, 153));
        jButton7.setText("Sessions");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });

        jButton8.setBackground(new java.awt.Color(255, 153, 255));
        jButton8.setText("Add Working\nDays & Hours");
        jButton8.setToolTipText("");
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });

        jButton9.setBackground(new java.awt.Color(153, 153, 153));
        jButton9.setText("Generate Time Table");
        jButton9.setToolTipText("");
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });

        jButton10.setBackground(new java.awt.Color(0, 255, 255));
        jButton10.setText("Location");
        jButton10.setToolTipText("");
        jButton10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton10ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButton3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton8, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton3, javax.swing.GroupLayout.DEFAULT_SIZE, 48, Short.MAX_VALUE)
                    .addComponent(jButton7, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        jPanel3.setBackground(new java.awt.Color(102, 204, 255));

        jPanel4.setBackground(new java.awt.Color(153, 153, 153));
        jPanel4.setPreferredSize(new java.awt.Dimension(1254, 621));

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 204, 255));
        jLabel1.setText("Add Lecturer");

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel3.setText("Lecturer Name");

        LectureNameTF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LectureNameTFActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel4.setText("Employee ID");

        EmployeeIDTF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EmployeeIDTFActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel5.setText("Faculty");

        FacultyCB.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select", "faculty of Computing", "faculty of Engineering", "faculty of Architecture" }));

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel6.setText("Department");

        DepartmentCB.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select", "IT", "ISE", "CS" }));

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel7.setText("Center");

        CenterCB.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select", "Jaffna", "Malabe", "Kolupitiya", "Kandy" }));

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel8.setText("Building");

        BuildingCB.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select", "New Building", "Old Building", "C-Block", "B-Block" }));

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel9.setText("Level");

        LevelCB.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select", "1", "2", "3", "4", "5" }));

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel10.setText("Rank");

        RankTF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RankTFActionPerformed(evt);
            }
        });

        jButton12.setBackground(new java.awt.Color(255, 153, 102));
        jButton12.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton12.setText("GENERATE RANK");
        jButton12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton12ActionPerformed(evt);
            }
        });

        jButton13.setBackground(new java.awt.Color(255, 102, 102));
        jButton13.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton13.setText("DELETE");
        jButton13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton13ActionPerformed(evt);
            }
        });

        jButton14.setBackground(new java.awt.Color(0, 255, 153));
        jButton14.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton14.setText("SAVE");
        jButton14.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton14ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(700, 700, 700)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(232, 232, 232)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(120, 120, 120)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jButton12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(EmployeeIDTF)
                            .addComponent(LectureNameTF)
                            .addComponent(FacultyCB, 0, 200, Short.MAX_VALUE)
                            .addComponent(DepartmentCB, 0, 200, Short.MAX_VALUE))
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addGap(229, 229, 229)
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(120, 120, 120))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton13, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(136, 136, 136)))
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(CenterCB, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(BuildingCB, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(LevelCB, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(RankTF, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton14, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(53, 53, 53)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(CenterCB, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(LectureNameTF)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(EmployeeIDTF, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(FacultyCB, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(DepartmentCB, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(RankTF, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(BuildingCB, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(LevelCB, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 93, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton13, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton12, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton14, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(50, 50, 50))
        );

        jTabbedPane2.addTab("Add Lecturer", jPanel4);

        jPanel5.setBackground(new java.awt.Color(153, 153, 153));

        jLabel11.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(102, 204, 255));
        jLabel11.setText("Manage Lecturers");

        jTblManageLecturers.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.gray, java.awt.Color.lightGray, java.awt.Color.black, java.awt.Color.darkGray));
        jTblManageLecturers.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "              ID", "    Lecturer Name", "      Employee ID", "           Faculty", "        Department", "           Center", "           Building", "            Levels", "            Ranks"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.Short.class, java.lang.String.class, java.lang.Integer.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTblManageLecturers.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTblManageLecturersMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTblManageLecturers);

        jButton1.setBackground(new java.awt.Color(0, 204, 255));
        jButton1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton1.setText("UPDATE");
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setBackground(new java.awt.Color(255, 102, 102));
        jButton2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton2.setText("DELETE");
        jButton2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton2MouseClicked(evt);
            }
        });
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton11.setBackground(new java.awt.Color(255, 153, 102));
        jButton11.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton11.setText("CLEAR");
        jButton11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton11ActionPerformed(evt);
            }
        });

        jLabel12.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel12.setText("Lecturer Name");

        jTF4EmployeeID.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jTF4EmployeeIDMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jTF4EmployeeIDMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jTF4EmployeeIDMouseReleased(evt);
            }
        });
        jTF4EmployeeID.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTF4EmployeeIDKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTF4EmployeeIDKeyTyped(evt);
            }
        });

        jLabel13.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel13.setText("Faculty");

        jCB6Faculty.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select", "faculty of Computing", "faculty of Engineering", "faculty of Architecture" }));

        jLabel14.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel14.setText("Department");

        jCB7Department.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select", "IT", "ISE", "CS" }));

        jLabel15.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel15.setText("Center");

        jCB8Center.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select", "Jaffna", "Malabe", "Kolupitiya", "Kandy" }));

        jLabel16.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel16.setText("Building");

        jCB9Building.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select", "New Building", "Old Building", "C-Block", "B-Block" }));

        jLabel17.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel17.setText("Level");

        jCB10Level.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select", "1", "2", "3", "4", "5" }));
        jCB10Level.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                jCB10LevelMouseMoved(evt);
            }
        });
        jCB10Level.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jCB10LevelMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jCB10LevelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jCB10LevelMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jCB10LevelMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jCB10LevelMouseReleased(evt);
            }
        });
        jCB10Level.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jCB10LevelKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jCB10LevelKeyReleased(evt);
            }
        });

        jLabel18.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel18.setText("Rank");

        jTF5Rank.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTF5RankActionPerformed(evt);
            }
        });

        jLabel19.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel19.setText("Employee ID");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(700, 700, 700)
                        .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(200, 200, 200)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 900, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(jLabel12, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(jLabel19, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(jLabel13, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                        .addGap(61, 61, 61))
                                    .addGroup(jPanel5Layout.createSequentialGroup()
                                        .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(36, 36, 36)))
                                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                                        .addComponent(jCB7Department, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGap(225, 225, 225)
                                        .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(30, 30, 30)
                                        .addComponent(jTF5Rank, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                .addComponent(jTF4EmployeeID, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(jCB6Faculty, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                            .addComponent(jTF6LectureName, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(225, 225, 225)
                                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(30, 30, 30)
                                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jCB10Level, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                .addComponent(jCB8Center, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(jCB9Building, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)))))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton11, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(200, 200, 200))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(50, 50, 50)
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(50, 50, 50)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jCB8Center, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jButton11, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTF6LectureName, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(18, 18, 18)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTF4EmployeeID, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jCB9Building, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jCB10Level, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jCB6Faculty, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jCB7Department, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTF5Rank, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        jTabbedPane2.addTab("Manage Lecturers", jPanel5);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 621, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        Lecturers lec = new   Lecturers();
        lec.setVisible(true);
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        Tags tag = new   Tags();
        tag.setVisible(true);
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        Sessions sub = new   Sessions();
        sub.setVisible(true);
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        Add_Working_Days_and_Hours Awd = new   Add_Working_Days_and_Hours();
        Awd.setVisible(true);
    }//GEN-LAST:event_jButton8ActionPerformed

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton9ActionPerformed

    private void jButton10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton10ActionPerformed
        Locations loca = new   Locations();
        loca.setVisible(true);
    }//GEN-LAST:event_jButton10ActionPerformed

    private void LectureNameTFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LectureNameTFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_LectureNameTFActionPerformed

    private void EmployeeIDTFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EmployeeIDTFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_EmployeeIDTFActionPerformed

    private void RankTFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RankTFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_RankTFActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        DefaultTableModel tblModel = (DefaultTableModel)jTblManageLecturers.getModel();
        if(jTblManageLecturers.getSelectedRowCount()==1){
              String LecturerName = jTF6LectureName.getText();
              String EmployeeID = jTF4EmployeeID.getText();
              String Faculty = jCB6Faculty.getSelectedItem().toString();
              String Department = jCB7Department.getSelectedItem().toString();
              String Center = jCB8Center.getSelectedItem().toString();
              String Building = jCB9Building.getSelectedItem().toString();
              String Level = jCB10Level.getSelectedItem().toString();
              String Rank = jTF5Rank.getText();
        
        tblModel.setValueAt(LecturerName, jTblManageLecturers.getSelectedRow(), 1);
        tblModel.setValueAt(EmployeeID, jTblManageLecturers.getSelectedRow(), 2);
        tblModel.setValueAt(Faculty, jTblManageLecturers.getSelectedRow(), 3);
        tblModel.setValueAt(Department, jTblManageLecturers.getSelectedRow(), 4);
        tblModel.setValueAt(Center, jTblManageLecturers.getSelectedRow(), 5);
        tblModel.setValueAt(Building, jTblManageLecturers.getSelectedRow(), 6);
        tblModel.setValueAt(Level, jTblManageLecturers.getSelectedRow(), 7);
        tblModel.setValueAt(Rank, jTblManageLecturers.getSelectedRow(), 8);
        
       int row = jTblManageLecturers.getSelectedRow();
       Integer ID = (Integer) jTblManageLecturers.getModel().getValueAt(row, 0);
       if(jTF6LectureName.getText().equals("") || jTF4EmployeeID.getText().equals("") || jCB6Faculty.getSelectedItem().toString().equals("Select") || jCB7Department.getSelectedItem().toString().equals("Select") || jCB8Center.getSelectedItem().toString().equals("Select") || jCB9Building.getSelectedItem().toString().equals("Select") || jCB10Level.getSelectedItem().toString().equals("Select") || jTF5Rank.getText().equals("") ){
                JOptionPane.showMessageDialog(this,"Please fill all the fields");
          
        
        }
        else{
        Lecturers.insertUpdateDeleteLecturers_Model('u',ID, LecturerName, EmployeeID, Faculty, Department, Center, Building, Level, Rank);  
      
        }
        }
         
      
        else
        {
            if(jTblManageLecturers.getRowCount()==0){
                JOptionPane.showMessageDialog(this, "Table is empty !!!");
            }else{
                JOptionPane.showMessageDialog(this, "Please Select a Single Row for Update  !!!");
            }
        }
//        try{
//           Class.forName("com.mysql.jdbc.Driver");
//               Connection con = DbConnection.dbconnect();
//               int row = jTblManageLecturers.getSelectedRow();
//              Integer ID = (Integer) jTblManageLecturers.getModel().getValueAt(row, 0);
//              String LecturerName = jTF6LectureName.getText();
//              String EmployeeID = jTF4EmployeeID.getText();
//              String Faculty = jCB6Faculty.getSelectedItem().toString();
//              String Department = jCB7Department.getSelectedItem().toString();
//              String Center = jCB8Center.getSelectedItem().toString();
//              String Building = jCB9Building.getSelectedItem().toString();
//              String Level = jCB10Level.getSelectedItem().toString();
//              String Rank = jTF5Rank.getText();
              
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
    Students st = new   Students();
    st.setVisible(true);
    
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton14ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton14ActionPerformed
        
        
        String LecturerName  = LectureNameTF.getText();
        String EmployeeID = EmployeeIDTF.getText();
        String Faculty = FacultyCB.getSelectedItem().toString();
        String Department = DepartmentCB.getSelectedItem().toString();
        String Center = CenterCB.getSelectedItem().toString();
        String Building = BuildingCB.getSelectedItem().toString();
        String Level = LevelCB.getSelectedItem().toString(); 
        String Rank = RankTF.getText();
    
        if(LectureNameTF.getText().equals("") || EmployeeIDTF.getText().equals("") || FacultyCB.getSelectedItem().toString().equals("Select") || DepartmentCB.getSelectedItem().toString().equals("Select") || CenterCB.getSelectedItem().toString().equals("Select") || BuildingCB.getSelectedItem().toString().equals("Select") || LevelCB.getSelectedItem().toString().equals("Select") || RankTF.getText().equals("") ){
                JOptionPane.showMessageDialog(this,"Please fill all the fields");
          
        
        }
        else{
        Lecturers.insertUpdateDeleteLecturers_Model('i',null,LecturerName,EmployeeID,Faculty,Department,Center,Building,Level,Rank);
        }
        jTblManageLecturers.setModel(new DefaultTableModel(null,new Object[]{ID,"Lecturer_Name","Employee_ID","Faculty","Department","Center","Building","Levels","Ranks"}));

        try{
               Class.forName("com.mysql.jdbc.Driver");
               Connection con = DbConnection.dbconnect();
               DefaultTableModel tblModel = (DefaultTableModel)jTblManageLecturers.getModel();
               Statement st=con.createStatement();
               ResultSet rs = st.executeQuery("SELECT * FROM hniti.manage_lecturers");
               while(rs.next()){
                   
                    
       
                   Integer ID = rs.getInt("ID");
                   LecturerName = rs.getString("Lecturer_Name");
                   EmployeeID = rs.getString("Employee_ID");
                   Faculty = rs.getString("Faculty");
                   Department = rs.getString("Department");
                   Center = rs.getString("Center");
                   Building = rs.getString("Building");
                   Level = rs.getString("Levels");
                   Rank = rs.getString("Ranks");
                   
               
                  tblModel.addRow(new Object[]{ID, LecturerName, EmployeeID, Faculty, Department, Center, Building, Level, Rank});
               }
                 
                    
            
               jTblManageLecturers.setModel(tblModel);
            }
               

        catch(Exception e){
            
        }
        
    }//GEN-LAST:event_jButton14ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        Subjects sub = new   Subjects();
        sub.setVisible(true);
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton12ActionPerformed
        // TODO add your handling code here:
        if(EmployeeIDTF.getText().equals("") || LevelCB.getSelectedItem().toString().equals("Select") ){
            JOptionPane.showMessageDialog(this,"Please Check Employee ID or Level field !!!");
        }else{
        RankTF.setText(LevelCB.getSelectedItem().toString() +"."+EmployeeIDTF.getText() );
        }
    }//GEN-LAST:event_jButton12ActionPerformed

    private void jButton13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton13ActionPerformed
        // TODO add your handling code here:
        LectureNameTF.setText("");
        EmployeeIDTF.setText("");
        FacultyCB.setSelectedItem("Select");
        DepartmentCB.setSelectedItem("Select");
        CenterCB.setSelectedItem("Select");
        BuildingCB.setSelectedItem("Select");
        LevelCB.setSelectedItem("Select");
        RankTF.setText("");
    }//GEN-LAST:event_jButton13ActionPerformed

    private void jTblManageLecturersMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTblManageLecturersMouseClicked
        DefaultTableModel tblModel=(DefaultTableModel)jTblManageLecturers.getModel();
        int rowIndex = jTblManageLecturers.getSelectedRow();
        jTF6LectureName.setText(tblModel.getValueAt(rowIndex,1).toString());
        jTF4EmployeeID.setText(tblModel.getValueAt(rowIndex,2).toString());
        jCB6Faculty.setSelectedItem(tblModel.getValueAt(rowIndex,3).toString());
        jCB7Department.setSelectedItem(tblModel.getValueAt(rowIndex,4).toString());
        jCB8Center.setSelectedItem(tblModel.getValueAt(rowIndex,5).toString());
        jCB9Building.setSelectedItem(tblModel.getValueAt(rowIndex,6).toString());
        jCB10Level.setSelectedItem(tblModel.getValueAt(rowIndex,7).toString());
        jTF5Rank.setText(tblModel.getValueAt(rowIndex,8).toString());

    }//GEN-LAST:event_jTblManageLecturersMouseClicked

    private void jCB10LevelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jCB10LevelMouseClicked
      if(jTF4EmployeeID.getText().equals("") || jCB10Level.getSelectedItem().toString().equals("Select") ){
            JOptionPane.showMessageDialog(this,"Please Check Employee ID or Level field !!!");
        }else{
        jTF5Rank.setText(jCB10Level.getSelectedItem().toString() +"."+jTF4EmployeeID.getText() );
        }
    }//GEN-LAST:event_jCB10LevelMouseClicked

    private void jTF5RankActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTF5RankActionPerformed
       
    }//GEN-LAST:event_jTF5RankActionPerformed

    private void jCB10LevelMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jCB10LevelMouseReleased
      
    }//GEN-LAST:event_jCB10LevelMouseReleased

    private void jTF4EmployeeIDMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTF4EmployeeIDMouseReleased
      
    }//GEN-LAST:event_jTF4EmployeeIDMouseReleased

    private void jTF4EmployeeIDMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTF4EmployeeIDMousePressed
        
    }//GEN-LAST:event_jTF4EmployeeIDMousePressed

    private void jCB10LevelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jCB10LevelMouseExited
       
    }//GEN-LAST:event_jCB10LevelMouseExited

    private void jTF4EmployeeIDMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTF4EmployeeIDMouseExited
       
    }//GEN-LAST:event_jTF4EmployeeIDMouseExited

    private void jCB10LevelMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jCB10LevelMousePressed
     
    }//GEN-LAST:event_jCB10LevelMousePressed

    private void jCB10LevelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jCB10LevelMouseEntered
       
    }//GEN-LAST:event_jCB10LevelMouseEntered

    private void jTF4EmployeeIDKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTF4EmployeeIDKeyTyped
      
    }//GEN-LAST:event_jTF4EmployeeIDKeyTyped

    private void jCB10LevelKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jCB10LevelKeyPressed
        
    }//GEN-LAST:event_jCB10LevelKeyPressed

    private void jCB10LevelKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jCB10LevelKeyReleased
         
    }//GEN-LAST:event_jCB10LevelKeyReleased

    private void jTF4EmployeeIDKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTF4EmployeeIDKeyReleased
         if(jTF4EmployeeID.getText().equals("") || jCB10Level.getSelectedItem().toString().equals("Select") ){
            JOptionPane.showMessageDialog(this,"Please Check Employee ID or Level field !!!");
        }else{
        jTF5Rank.setText(jCB10Level.getSelectedItem().toString() +"."+jTF4EmployeeID.getText() );
        }
    }//GEN-LAST:event_jTF4EmployeeIDKeyReleased

    private void jCB10LevelMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jCB10LevelMouseMoved
         if(jTF4EmployeeID.getText().equals("") || jCB10Level.getSelectedItem().toString().equals("Select") ){
            JOptionPane.showMessageDialog(this,"Please Check Employee ID or Level field !!!");
        }else{
        jTF5Rank.setText(jCB10Level.getSelectedItem().toString() +"."+jTF4EmployeeID.getText() );
        }
    }//GEN-LAST:event_jCB10LevelMouseMoved

    private void jButton11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton11ActionPerformed
        jTF6LectureName.setText("");
        jTF4EmployeeID.setText("");
        jCB6Faculty.setSelectedItem("Select");
        jCB7Department.setSelectedItem("Select");
        jCB8Center.setSelectedItem("Select");
        jCB9Building.setSelectedItem("Select");
        jCB10Level.setSelectedItem("Select");
        jTF5Rank.setText("");
        
                jTblManageLecturers.setModel(new DefaultTableModel(null,new Object[]{ID,"Lecturer_Name","Employee_ID","Faculty","Department","Center","Building","Levels","Ranks"}));

        try{
               Class.forName("com.mysql.jdbc.Driver");
               Connection con = DbConnection.dbconnect();
               DefaultTableModel tblModel = (DefaultTableModel)jTblManageLecturers.getModel();
               Statement st=con.createStatement();
               ResultSet rs = st.executeQuery("SELECT * FROM hniti.manage_lecturers");
               while(rs.next()){
                   
                    
       
                   Integer ID = rs.getInt("ID");
                 String  LecturerName = rs.getString("Lecturer_Name");
                  String EmployeeID = rs.getString("Employee_ID");
                  String Faculty = rs.getString("Faculty");
                   String Department = rs.getString("Department");
                  String Center = rs.getString("Center");
                   String Building = rs.getString("Building");
                   String Level = rs.getString("Levels");
                   String Rank = rs.getString("Ranks");
                   
               
                  tblModel.addRow(new Object[]{ID, LecturerName, EmployeeID, Faculty, Department, Center, Building, Level, Rank});
               }
                 
                    
            
               jTblManageLecturers.setModel(tblModel);
            }
     

        catch(Exception e){
            
        }
    }//GEN-LAST:event_jButton11ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
      if(jTblManageLecturers.getSelectedRowCount()==1){
        DefaultTableModel tblModel = (DefaultTableModel)jTblManageLecturers.getModel();
        String LecturerName  = LectureNameTF.getText();
        String EmployeeID = EmployeeIDTF.getText();
        String Faculty = FacultyCB.getSelectedItem().toString();
        String Department = DepartmentCB.getSelectedItem().toString();
        String Center = CenterCB.getSelectedItem().toString();
        String Building = BuildingCB.getSelectedItem().toString();
        String Level = LevelCB.getSelectedItem().toString(); 
        String Rank = RankTF.getText();
        
      
        
        
        int row = jTblManageLecturers.getSelectedRow();
             
        Integer ID = (Integer) jTblManageLecturers.getModel().getValueAt(row, 0);
        Lecturers.insertUpdateDeleteLecturers_Model('d', ID, LecturerName, EmployeeID, Faculty, Department, Center, Building,Level,Rank);
        
        }
        
        jTblManageLecturers.setModel(new DefaultTableModel(null,new Object[]{ID,"Lecturer_Name","Employee_ID","Faculty","Department","Center","Building","Levels","Ranks"}));  
        
            try{
               Class.forName("com.mysql.jdbc.Driver");
               Connection con = DbConnection.dbconnect();
               DefaultTableModel tblModel = (DefaultTableModel)jTblManageLecturers.getModel();
               Statement st=con.createStatement();
               ResultSet rs = st.executeQuery("SELECT * FROM hniti.manage_lecturers");
               while(rs.next()){
                   
                    
       
                   Integer ID = rs.getInt("ID");
                 String  LecturerName = rs.getString("Lecturer_Name");
                  String EmployeeID = rs.getString("Employee_ID");
                  String Faculty = rs.getString("Faculty");
                   String Department = rs.getString("Department");
                  String Center = rs.getString("Center");
                   String Building = rs.getString("Building");
                   String Level = rs.getString("Levels");
                   String Rank = rs.getString("Ranks");
                   
               
                  tblModel.addRow(new Object[]{ID, LecturerName, EmployeeID, Faculty, Department, Center, Building, Level, Rank});
               }
                 
                    
            
               jTblManageLecturers.setModel(tblModel);
            }
     

        catch(Exception e){
            
        }
     
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton2MouseClicked
        
    }//GEN-LAST:event_jButton2MouseClicked

    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked
       
    }//GEN-LAST:event_jButton1MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Lecturers.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Lecturers.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Lecturers.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Lecturers.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Lecturers().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> BuildingCB;
    private javax.swing.JComboBox<String> CenterCB;
    private javax.swing.JComboBox<String> DepartmentCB;
    private javax.swing.JTextField EmployeeIDTF;
    private javax.swing.JComboBox<String> FacultyCB;
    private javax.swing.JTextField LectureNameTF;
    private javax.swing.JComboBox<String> LevelCB;
    private javax.swing.JTextField RankTF;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton11;
    private javax.swing.JButton jButton12;
    private javax.swing.JButton jButton13;
    private javax.swing.JButton jButton14;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JComboBox<String> jCB10Level;
    private javax.swing.JComboBox<String> jCB6Faculty;
    private javax.swing.JComboBox<String> jCB7Department;
    private javax.swing.JComboBox<String> jCB8Center;
    private javax.swing.JComboBox<String> jCB9Building;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTF4EmployeeID;
    private javax.swing.JTextField jTF5Rank;
    private javax.swing.JTextField jTF6LectureName;
    private javax.swing.JTabbedPane jTabbedPane2;
    private javax.swing.JTable jTblManageLecturers;
    // End of variables declaration//GEN-END:variables
}
